freebsd_instance:
  image: freebsd-12-2-release-amd64

task:
  env:
    HOME: /tmp  # cargo cache needs it
    # Temporary workaround for https://github.com/rust-lang/rustup/issues/2774
    RUSTUP_IO_THREADS: 1
  matrix:
    - name: FreeBSD 12 amd64 nightly
      env:
        VERSION: nightly
    - name: FreeBSD 12 amd64 MSRV
      env:
        VERSION: 1.46.0
  # Install Rust
  setup_script:
    - fetch https://sh.rustup.rs -o rustup.sh
    - sh rustup.sh -y
    - $HOME/.cargo/bin/rustup toolchain install $VERSION
    # In 12.2, aio on ufs is considered unsafe
    - sysctl vfs.aio.enable_unsafe=1
  cargo_cache:
    folder: $HOME/.cargo/registry
    fingerprint_script: cat Cargo.lock || echo ""
  test_script:
    - . $HOME/.cargo/env
    - cargo +$VERSION test
  # Test our minimal version spec.
  minver_test_script:
    - . $HOME/.cargo/env
    - if [ "$VERSION" = "nightly" ]; then cargo +$VERSION update -Zminimal-versions; else true; fi
    - if [ "$VERSION" = "nightly" ]; then cargo +$VERSION check --all-targets; else true; fi
  clippy_script:
    - . $HOME/.cargo/env
    - if [ "$VERSION" = "nightly" ]; then cargo +$VERSION clippy --all-targets -- -D warnings; else true; fi
  before_cache_script: rm -rf $HOME/.cargo/registry/index
