freebsd_instance:
  image: freebsd-14-4-release-amd64-ufs

setup: &SETUP
  env:
    HOME: /tmp  # cargo cache needs it
    RUST_BACKTRACE: full  # Better info for debugging test failures
  # Install Rust
  setup_script:
    - fetch https://sh.rustup.rs -o rustup.sh
    - sh rustup.sh -y --default-toolchain $VERSION
    # aio on ufs is considered unsafe
    - sysctl vfs.aio.enable_unsafe=1
  cargo_cache:
    folder: $HOME/.cargo/registry
    fingerprint_script: cat Cargo.lock || echo ""

# Check that we compile with the MSRV.  But the tests don't need to.
msrv_task:
  name: FreeBSD 14 amd64 MSRV
  env:
    VERSION: 1.71.0
  << : *SETUP
  check_script:
    - . $HOME/.cargo/env
    - cargo +$VERSION build
  before_cache_script: rm -rf $HOME/.cargo/registry/index

nightly_task:
  name: FreeBSD 14 amd64 nightly
  env:
    VERSION: nightly
  << : *SETUP
  nightly_setup_script:
    pkg install -y cargo-audit
  test_script:
    - . $HOME/.cargo/env
    - cargo +$VERSION test
  clippy_script:
    - . $HOME/.cargo/env
    - if [ "$VERSION" = "nightly" ]; then cargo +$VERSION clippy --all-targets -- -D warnings; else true; fi
  audit_script:
    - . $HOME/.cargo/env
    - cargo audit
  # Test our minimal version spec.
  minver_test_script:
    - . $HOME/.cargo/env
    - if [ "$VERSION" = "nightly" ]; then cargo +$VERSION update -Zdirect-minimal-versions; else true; fi
    - if [ "$VERSION" = "nightly" ]; then cargo +$VERSION check --all-targets; else true; fi
  fmt_script:
    - . $HOME/.cargo/env
    - if [ "$VERSION" = "nightly" ]; then cargo +$VERSION fmt -- --check; fi
  before_cache_script: rm -rf $HOME/.cargo/registry/index
