freebsd_instance:
  image: freebsd-11-2-release-amd64

task:
  name: cargo test
  # Install Rust
  setup_script:
    - pkg install -y curl
    - curl https://sh.rustup.rs -sSf --output rustup.sh
    - sh rustup.sh -y
    # In 11.2, aio on ufs is considered unsafe
    - sysctl vfs.aio.enable_unsafe=1
  test_script:
    - . $HOME/.cargo/env
    - cargo test
