setup: &SETUP
  env:
    HOME: /tmp # cargo needs it
  setup_script:
    - fetch https://sh.rustup.rs -o rustup.sh
    - sh rustup.sh -y --profile=${PROFILE} --default-toolchain ${VERSION}-x86_64-unknown-freebsd

build: &BUILD
  cargo_cache:
    folder: $HOME/.cargo/registry
    fingerprint_script: cat Cargo.lock || echo ""
  build_script:
    - . $HOME/.cargo/env || true
    - cargo --version
    - cargo build --all

task:
  use_compute_credits: $CIRRUS_USER_COLLABORATOR == 'true'
  name: FreeBSD 14 nightly
  env:
    PROFILE: minimal
    matrix:
      RUST_BACKTRACE: full
      RUST_BACKTRACE: 0
    matrix:
      VERSION: nightly-2024-01-16
      VERSION: nightly-2024-01-17
      VERSION: nightly-2024-01-18
      VERSION: nightly-2024-01-19
      VERSION: nightly-2024-01-20
      VERSION: nightly-2024-01-21
      VERSION: nightly-2024-01-22
  name: FreeBSD 14.2
  freebsd_instance:
    image: freebsd-14-2-release-amd64-ufs
  << : *SETUP
  << : *BUILD
  before_cache_script: rm -rf $HOME/.cargo/registry/index
