freebsd_instance:
  image: freebsd-11-3-stable-amd64-v20190801

task:
  name: cargo test
  # Install Rust
  setup_script:
    - fetch https://sh.rustup.rs -o rustup.sh
    - sh rustup.sh -y
    # In 11.3, aio on ufs is considered unsafe
    - sysctl vfs.aio.enable_unsafe=1
  test_script:
    - . $HOME/.cargo/env
    - cargo test
