[package]
name = "mio-aio"
version = "0.4.1-pre"
authors = ["Alan Somers <asomers@gmail.com>"]
license = "MIT/Apache-2.0"
readme = "README.md"
repository = "https://github.com/asomers/mio-aio"
description = """
POSIX AIO bindings for mio
"""
categories = ["asynchronous", "filesystem"]
keywords = ["io", "async", "non-blocking", "aio"]
documentation = "https://asomers.github.io/mio-aio/mio_aio/"

[dependencies]
mio = "0.6.13"
nix = "0.12.0"

[dev-dependencies]
divbuf = "0.2.0"
log = "0.3.1"
sysctl = "0.1"
tempfile = "2"

[[test]]
name = "functional"
path = "tests/test.rs"

[[test]]
name = "lio_listio_incomplete"
path = "tests/lio_listio_incomplete.rs"
