[package]
name = "mio-aio"
version = "0.4.2-pre"
authors = ["Alan Somers <asomers@gmail.com>"]
license = "MIT/Apache-2.0"
readme = "README.md"
repository = "https://github.com/asomers/mio-aio"
description = """
POSIX AIO bindings for mio
"""
categories = ["asynchronous", "filesystem"]
keywords = ["io", "async", "non-blocking", "aio"]
documentation = "https://asomers.github.io/mio-aio/mio_aio/"

[dependencies]
mio = "0.6.13"
nix = { git = "https://github.com/asomers/nix", rev = "5d2354517a643162bdc6608a5a30aba43f592069" }

[dev-dependencies]
divbuf = "0.2.0"
log = "0.3.4"
sysctl = "0.1"
tempfile = "3.0"

[[test]]
name = "functional"
path = "tests/test.rs"

[[test]]
name = "lio_listio_incomplete"
path = "tests/lio_listio_incomplete.rs"
