[package]
name = "mio-aio"
edition = "2018"
version = "0.5.0"
authors = ["Alan Somers <asomers@gmail.com>"]
license = "MIT/Apache-2.0"
readme = "README.md"
repository = "https://github.com/asomers/mio-aio"
description = """
POSIX AIO bindings for mio
"""
categories = ["asynchronous", "filesystem"]
keywords = ["io", "async", "non-blocking", "aio"]
documentation = "https://asomers.github.io/mio-aio/mio_aio/"
exclude = ["release.toml"]

[package.metadata.docs.rs]
targets = [
  "x86_64-unknown-freebsd",
]

[dependencies]
mio = "0.6.13"
nix = "0.22.0"

[dev-dependencies]
assert-impl = "0.1"
log = "0.3.4"
sysctl = "0.1"
tempfile = "3.0"

[[test]]
name = "functional"
path = "tests/test.rs"

[[test]]
name = "lio_listio_incomplete"
path = "tests/lio_listio_incomplete.rs"
