[package]
name = "mio-aio"
version = "0.2.0-pre"
authors = ["Alan Somers <asomers@gmail.com>"]
license = "MIT/Apache-2.0"
readme = "README.md"
repository = "https://github.com/asomers/mio-aio"
description = """
POSIX AIO bindings for mio
"""
categories = ["asynchronous", "filesystem"]
keywords = ["io", "async", "non-blocking", "aio"]

[dependencies]
mio = "0.6.13"
nix = { git = "https://github.com/asomers/nix", rev = "71fe963" }

[dev-dependencies]
divbuf = { git = "https://github.com/asomers/divbuf", rev = "70104b4" }
log = "0.3.1"
tempfile = "2"
