[package]
name = "mio-aio"
version = "0.2.0-pre"
authors = ["Alan Somers <asomers@gmail.com>"]
license = "MIT/Apache-2.0"
readme = "README.md"
repository = "https://github.com/asomers/mio-aio"
description = """
POSIX AIO bindings for mio
"""
categories = ["asynchronous", "filesystem"]
keywords = ["io", "async", "non-blocking", "aio"]

[dependencies]
bytes = "0.4.5"
libc = "0.2"
mio = { path = "/home/somers/src/rust/mio" }
nix = { path = "/home/somers/src/rust/nix" }

[dev-dependencies]
tempfile = "2"
log = "0.3.1"
env_logger = { version = "0.3.0", default-features = false }
