[package]
name = "mio-aio"
version = "0.1.0"
authors = ["Alan Somers <asomers@gmail.com>"]
license = "MIT/Apache-2.0"
readme = "README.md"
respository = "https://github.com/asomers/mio-aio"
homepage = "https://github.com/asomers/mio-aio"
description = """
POSIX AIO bindings for mio
"""
categories = ["asynchronous", "filesystems"]

[dependencies]
libc = "0.2"
mio = { git = "https://github.com/asomers/mio", branch = "aio6" }
nix = { git = "https://github.com/nix-rust/nix", rev = "2f780ef" }

[dev-dependencies]
tempfile = "2"
log = "0.3.1"
env_logger = { version = "0.3.0", default-features = false }
